name: Ruby

on:
  push:
    branches:
      - develop

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.5'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        RAILS_LOG_TO_STDOUT: true
      run: bundle exec rake
